-- Boost colorscheme - Plugin highlight groups
-- Covers all plugins in LazyVim setup

local M = {}

function M.get(p)
  return {
    -- ============================================
    -- bufferline.nvim
    -- ============================================
    BufferLineFill = { bg = p.bg },
    BufferLineBackground = { fg = p.fg_muted, bg = p.bg_element },
    BufferLineBuffer = { fg = p.fg_muted, bg = p.bg_element },
    BufferLineBufferSelected = { fg = p.fg, bg = p.bg, bold = true },
    BufferLineBufferVisible = { fg = p.fg_muted, bg = p.bg_elevated },
    BufferLineCloseButton = { fg = p.fg_muted, bg = p.bg_element },
    BufferLineCloseButtonSelected = { fg = p.error_light, bg = p.bg },
    BufferLineCloseButtonVisible = { fg = p.fg_muted, bg = p.bg_elevated },
    BufferLineModified = { fg = p.warning_light, bg = p.bg_element },
    BufferLineModifiedSelected = { fg = p.warning_light, bg = p.bg },
    BufferLineModifiedVisible = { fg = p.warning_light, bg = p.bg_elevated },
    BufferLineDuplicate = { fg = p.dark200, bg = p.bg_element, italic = true },
    BufferLineDuplicateSelected = { fg = p.dark100, bg = p.bg, italic = true },
    BufferLineDuplicateVisible = { fg = p.dark200, bg = p.bg_elevated, italic = true },
    BufferLineSeparator = { fg = p.bg, bg = p.bg_element },
    BufferLineSeparatorSelected = { fg = p.bg, bg = p.bg },
    BufferLineSeparatorVisible = { fg = p.bg, bg = p.bg_elevated },
    BufferLineIndicatorSelected = { fg = p.gold500, bg = p.bg },
    BufferLineIndicatorVisible = { fg = p.dark300, bg = p.bg_elevated },
    BufferLineTab = { fg = p.fg_muted, bg = p.bg_element },
    BufferLineTabSelected = { fg = p.fg, bg = p.bg, bold = true },
    BufferLineTabClose = { fg = p.error_light, bg = p.bg },
    BufferLinePick = { fg = p.gold500, bg = p.bg_element, bold = true },
    BufferLinePickSelected = { fg = p.gold400, bg = p.bg, bold = true },
    BufferLinePickVisible = { fg = p.gold500, bg = p.bg_elevated, bold = true },
    BufferLineError = { fg = p.error_light, bg = p.bg_element },
    BufferLineErrorSelected = { fg = p.error_light, bg = p.bg },
    BufferLineErrorDiagnostic = { fg = p.error_light, bg = p.bg_element },
    BufferLineErrorDiagnosticSelected = { fg = p.error_light, bg = p.bg },
    BufferLineWarning = { fg = p.warning_light, bg = p.bg_element },
    BufferLineWarningSelected = { fg = p.warning_light, bg = p.bg },
    BufferLineWarningDiagnostic = { fg = p.warning_light, bg = p.bg_element },
    BufferLineWarningDiagnosticSelected = { fg = p.warning_light, bg = p.bg },
    BufferLineInfo = { fg = p.info_light, bg = p.bg_element },
    BufferLineInfoSelected = { fg = p.info_light, bg = p.bg },
    BufferLineInfoDiagnostic = { fg = p.info_light, bg = p.bg_element },
    BufferLineInfoDiagnosticSelected = { fg = p.info_light, bg = p.bg },
    BufferLineHint = { fg = p.hint, bg = p.bg_element },
    BufferLineHintSelected = { fg = p.hint, bg = p.bg },
    BufferLineHintDiagnostic = { fg = p.hint, bg = p.bg_element },
    BufferLineHintDiagnosticSelected = { fg = p.hint, bg = p.bg },
    BufferLineNumbers = { fg = p.fg_muted, bg = p.bg_element },
    BufferLineNumbersSelected = { fg = p.gold500, bg = p.bg, bold = true },
    BufferLineNumbersVisible = { fg = p.fg_muted, bg = p.bg_elevated },

    -- ============================================
    -- gitsigns.nvim
    -- ============================================
    GitSignsAdd = { fg = p.git.add },
    GitSignsChange = { fg = p.git.change },
    GitSignsDelete = { fg = p.git.delete },
    GitSignsAddNr = { fg = p.git.add },
    GitSignsChangeNr = { fg = p.git.change },
    GitSignsDeleteNr = { fg = p.git.delete },
    GitSignsAddLn = { bg = p.success_bg },
    GitSignsChangeLn = { bg = p.info_bg },
    GitSignsDeleteLn = { bg = p.error_bg },
    GitSignsAddPreview = { fg = p.git.add, bg = p.success_bg },
    GitSignsDeletePreview = { fg = p.git.delete, bg = p.error_bg },
    GitSignsCurrentLineBlame = { fg = p.dark100, italic = true },
    GitSignsAddInline = { bg = p.success_bg },
    GitSignsChangeInline = { bg = p.info_bg },
    GitSignsDeleteInline = { bg = p.error_bg },
    GitSignsDeleteVirtLn = { fg = p.git.delete, bg = p.error_bg },
    GitSignsDeleteVirtLnInLine = { fg = p.git.delete, bg = p.error_bg },
    GitSignsVirtLnum = { fg = p.dark200 },

    -- ============================================
    -- noice.nvim
    -- ============================================
    NoiceCmdline = { fg = p.fg, bg = p.bg_elevated },
    NoiceCmdlineIcon = { fg = p.gold500 },
    NoiceCmdlineIconSearch = { fg = p.warning_light },
    NoiceCmdlinePopup = { fg = p.fg, bg = p.bg_elevated },
    NoiceCmdlinePopupBorder = { fg = p.border },
    NoiceCmdlinePopupBorderSearch = { fg = p.warning_light },
    NoiceConfirm = { fg = p.fg, bg = p.bg_elevated },
    NoiceConfirmBorder = { fg = p.gold500 },
    NoiceCursor = { fg = p.bg, bg = p.gold500 },
    NoiceFormatConfirm = { fg = p.gold500, bold = true },
    NoiceFormatConfirmDefault = { fg = p.fg, bg = p.bg_element },
    NoiceFormatDate = { fg = p.info_light },
    NoiceFormatEvent = { fg = p.fg_muted },
    NoiceFormatKind = { fg = p.gold500 },
    NoiceFormatLevelDebug = { fg = p.fg_muted },
    NoiceFormatLevelError = { fg = p.error_light },
    NoiceFormatLevelInfo = { fg = p.info_light },
    NoiceFormatLevelOff = { fg = p.dark200 },
    NoiceFormatLevelTrace = { fg = p.fg_muted },
    NoiceFormatLevelWarn = { fg = p.warning_light },
    NoiceFormatProgressDone = { fg = p.bg, bg = p.gold500 },
    NoiceFormatProgressTodo = { fg = p.fg_muted, bg = p.bg_element },
    NoiceFormatTitle = { fg = p.gold500, bold = true },
    NoiceLspProgressClient = { fg = p.gold500, bold = true },
    NoiceLspProgressSpinner = { fg = p.gold400 },
    NoiceLspProgressTitle = { fg = p.fg },
    NoiceMini = { fg = p.fg, bg = p.bg_elevated },
    NoicePopup = { fg = p.fg, bg = p.bg_elevated },
    NoicePopupBorder = { fg = p.border },
    NoicePopupmenu = { fg = p.fg, bg = p.bg_elevated },
    NoicePopupmenuBorder = { fg = p.border },
    NoicePopupmenuMatch = { fg = p.gold500, bold = true },
    NoicePopupmenuSelected = { bg = p.bg_element },
    NoiceScrollbar = { bg = p.bg_element },
    NoiceScrollbarThumb = { bg = p.dark200 },
    NoiceSplit = { fg = p.fg, bg = p.bg },
    NoiceSplitBorder = { fg = p.border },
    NoiceVirtualText = { fg = p.fg_muted },

    -- ============================================
    -- nvim-notify (used by noice)
    -- ============================================
    NotifyBackground = { bg = p.bg },
    NotifyERRORBorder = { fg = p.error },
    NotifyWARNBorder = { fg = p.warning },
    NotifyINFOBorder = { fg = p.info },
    NotifyDEBUGBorder = { fg = p.fg_muted },
    NotifyTRACEBorder = { fg = p.dark200 },
    NotifyERRORIcon = { fg = p.error_light },
    NotifyWARNIcon = { fg = p.warning_light },
    NotifyINFOIcon = { fg = p.info_light },
    NotifyDEBUGIcon = { fg = p.fg_muted },
    NotifyTRACEIcon = { fg = p.dark100 },
    NotifyERRORTitle = { fg = p.error_light, bold = true },
    NotifyWARNTitle = { fg = p.warning_light, bold = true },
    NotifyINFOTitle = { fg = p.info_light, bold = true },
    NotifyDEBUGTitle = { fg = p.fg_muted, bold = true },
    NotifyTRACETitle = { fg = p.dark100, bold = true },
    NotifyERRORBody = { fg = p.fg },
    NotifyWARNBody = { fg = p.fg },
    NotifyINFOBody = { fg = p.fg },
    NotifyDEBUGBody = { fg = p.fg },
    NotifyTRACEBody = { fg = p.fg },

    -- ============================================
    -- which-key.nvim
    -- ============================================
    WhichKey = { fg = p.gold500 },
    WhichKeyBorder = { fg = p.border },
    WhichKeyDesc = { fg = p.fg },
    WhichKeyFloat = { bg = p.bg_elevated },
    WhichKeyGroup = { fg = p.gold400 },
    WhichKeyIcon = { fg = p.gold500 },
    WhichKeyIconAzure = { fg = p.info_light },
    WhichKeyIconBlue = { fg = p.info },
    WhichKeyIconCyan = { fg = "#00bcd4" },
    WhichKeyIconGreen = { fg = p.success_light },
    WhichKeyIconGrey = { fg = p.fg_muted },
    WhichKeyIconOrange = { fg = p.warning_light },
    WhichKeyIconPurple = { fg = "#9c27b0" },
    WhichKeyIconRed = { fg = p.error_light },
    WhichKeyIconYellow = { fg = p.gold500 },
    WhichKeyNormal = { fg = p.fg, bg = p.bg_elevated },
    WhichKeySeparator = { fg = p.dark200 },
    WhichKeyTitle = { fg = p.gold500, bold = true },
    WhichKeyValue = { fg = p.fg_muted },

    -- ============================================
    -- trouble.nvim
    -- ============================================
    TroubleCount = { fg = p.gold500, bold = true },
    TroubleCode = { fg = p.fg_muted },
    TroubleDirectory = { fg = p.gold500 },
    TroubleFilename = { fg = p.fg },
    TroubleFoldIcon = { fg = p.gold500 },
    TroubleIconArray = { fg = p.gold400 },
    TroubleIconBoolean = { fg = p.syntax.constant },
    TroubleIconClass = { fg = p.syntax.type },
    TroubleIconConstant = { fg = p.syntax.constant },
    TroubleIconConstructor = { fg = p.syntax.constructor },
    TroubleIconDirectory = { fg = p.gold500 },
    TroubleIconEnum = { fg = p.syntax.type },
    TroubleIconEnumMember = { fg = p.syntax.constant },
    TroubleIconEvent = { fg = p.syntax.type },
    TroubleIconField = { fg = p.syntax.field },
    TroubleIconFile = { fg = p.fg },
    TroubleIconFunction = { fg = p.syntax.func },
    TroubleIconInterface = { fg = p.syntax.type },
    TroubleIconKey = { fg = p.syntax.keyword },
    TroubleIconMethod = { fg = p.syntax.func },
    TroubleIconModule = { fg = p.syntax.namespace },
    TroubleIconNamespace = { fg = p.syntax.namespace },
    TroubleIconNull = { fg = p.syntax.constant },
    TroubleIconNumber = { fg = p.syntax.number },
    TroubleIconObject = { fg = p.syntax.type },
    TroubleIconOperator = { fg = p.syntax.operator },
    TroubleIconPackage = { fg = p.syntax.namespace },
    TroubleIconProperty = { fg = p.syntax.property },
    TroubleIconString = { fg = p.syntax.string },
    TroubleIconStruct = { fg = p.syntax.type },
    TroubleIconTypeParameter = { fg = p.syntax.type },
    TroubleIconVariable = { fg = p.syntax.variable },
    TroubleIndent = { fg = p.dark300 },
    TroubleIndentFoldClosed = { fg = p.gold500 },
    TroubleIndentFoldOpen = { fg = p.gold500 },
    TroubleIndentLast = { fg = p.dark300 },
    TroubleIndentMiddle = { fg = p.dark300 },
    TroubleIndentTop = { fg = p.dark300 },
    TroubleIndentWs = { fg = p.dark300 },
    TroubleNormal = { fg = p.fg, bg = p.bg },
    TroubleNormalNC = { fg = p.fg, bg = p.bg },
    TroublePos = { fg = p.fg_muted },
    TroublePreview = { bg = p.bg_visual },
    TroubleSource = { fg = p.fg_muted },
    TroubleText = { fg = p.fg },

    -- ============================================
    -- todo-comments.nvim
    -- ============================================
    TodoBgFIX = { fg = p.bg, bg = p.error_light, bold = true },
    TodoBgHACK = { fg = p.bg, bg = p.warning_light, bold = true },
    TodoBgNOTE = { fg = p.bg, bg = p.info_light, bold = true },
    TodoBgPERF = { fg = p.bg, bg = p.gold400, bold = true },
    TodoBgTEST = { fg = p.bg, bg = "#9c27b0", bold = true },
    TodoBgTODO = { fg = p.bg, bg = p.gold500, bold = true },
    TodoBgWARN = { fg = p.bg, bg = p.warning_light, bold = true },
    TodoFgFIX = { fg = p.error_light },
    TodoFgHACK = { fg = p.warning_light },
    TodoFgNOTE = { fg = p.info_light },
    TodoFgPERF = { fg = p.gold400 },
    TodoFgTEST = { fg = "#9c27b0" },
    TodoFgTODO = { fg = p.gold500 },
    TodoFgWARN = { fg = p.warning_light },
    TodoSignFIX = { fg = p.error_light },
    TodoSignHACK = { fg = p.warning_light },
    TodoSignNOTE = { fg = p.info_light },
    TodoSignPERF = { fg = p.gold400 },
    TodoSignTEST = { fg = "#9c27b0" },
    TodoSignTODO = { fg = p.gold500 },
    TodoSignWARN = { fg = p.warning_light },

    -- ============================================
    -- flash.nvim
    -- ============================================
    FlashBackdrop = { fg = p.dark200 },
    FlashCurrent = { fg = p.bg, bg = p.gold400, bold = true },
    FlashCursor = { reverse = true },
    FlashLabel = { fg = p.bg, bg = p.gold500, bold = true },
    FlashMatch = { fg = p.gold300, bg = p.bg_element },
    FlashPrompt = { link = "NoiceCmdline" },
    FlashPromptIcon = { fg = p.gold500 },

    -- ============================================
    -- blink.cmp
    -- ============================================
    BlinkCmpDoc = { fg = p.fg, bg = p.bg_elevated },
    BlinkCmpDocBorder = { fg = p.border, bg = p.bg_elevated },
    BlinkCmpDocCursorLine = { bg = p.bg_element },
    BlinkCmpDocSeparator = { fg = p.border },
    BlinkCmpGhostText = { fg = p.dark200, italic = true },
    BlinkCmpKind = { fg = p.gold500 },
    BlinkCmpKindArray = { fg = p.gold400 },
    BlinkCmpKindBoolean = { fg = p.syntax.constant },
    BlinkCmpKindClass = { fg = p.syntax.type },
    BlinkCmpKindCodeium = { fg = "#09b6a2" },
    BlinkCmpKindColor = { fg = p.gold400 },
    BlinkCmpKindConstant = { fg = p.syntax.constant },
    BlinkCmpKindConstructor = { fg = p.syntax.constructor },
    BlinkCmpKindCopilot = { fg = "#6cc644" },
    BlinkCmpKindDefault = { fg = p.fg_muted },
    BlinkCmpKindEnum = { fg = p.syntax.type },
    BlinkCmpKindEnumMember = { fg = p.syntax.constant },
    BlinkCmpKindEvent = { fg = p.syntax.type },
    BlinkCmpKindField = { fg = p.syntax.field },
    BlinkCmpKindFile = { fg = p.fg },
    BlinkCmpKindFolder = { fg = p.gold500 },
    BlinkCmpKindFunction = { fg = p.syntax.func },
    BlinkCmpKindInterface = { fg = p.syntax.type },
    BlinkCmpKindKey = { fg = p.syntax.keyword },
    BlinkCmpKindKeyword = { fg = p.syntax.keyword },
    BlinkCmpKindMethod = { fg = p.syntax.func },
    BlinkCmpKindModule = { fg = p.syntax.namespace },
    BlinkCmpKindNamespace = { fg = p.syntax.namespace },
    BlinkCmpKindNull = { fg = p.syntax.constant },
    BlinkCmpKindNumber = { fg = p.syntax.number },
    BlinkCmpKindObject = { fg = p.syntax.type },
    BlinkCmpKindOperator = { fg = p.syntax.operator },
    BlinkCmpKindPackage = { fg = p.syntax.namespace },
    BlinkCmpKindProperty = { fg = p.syntax.property },
    BlinkCmpKindReference = { fg = p.gold300 },
    BlinkCmpKindSnippet = { fg = p.gold400 },
    BlinkCmpKindString = { fg = p.syntax.string },
    BlinkCmpKindStruct = { fg = p.syntax.type },
    BlinkCmpKindSupermaven = { fg = "#68d5c8" },
    BlinkCmpKindTabNine = { fg = "#ca8a04" },
    BlinkCmpKindText = { fg = p.fg },
    BlinkCmpKindTypeParameter = { fg = p.syntax.type },
    BlinkCmpKindUnit = { fg = p.syntax.number },
    BlinkCmpKindValue = { fg = p.syntax.constant },
    BlinkCmpKindVariable = { fg = p.syntax.variable },
    BlinkCmpLabel = { fg = p.fg },
    BlinkCmpLabelDeprecated = { fg = p.fg_muted, strikethrough = true },
    BlinkCmpLabelDetail = { fg = p.fg_muted },
    BlinkCmpLabelMatch = { fg = p.gold500, bold = true },
    BlinkCmpMenu = { fg = p.fg, bg = p.bg_elevated },
    BlinkCmpMenuBorder = { fg = p.border, bg = p.bg_elevated },
    BlinkCmpMenuSelection = { bg = p.bg_element },
    BlinkCmpScrollBarGutter = { bg = p.bg_element },
    BlinkCmpScrollBarThumb = { bg = p.dark200 },
    BlinkCmpSignatureHelp = { fg = p.fg, bg = p.bg_elevated },
    BlinkCmpSignatureHelpBorder = { fg = p.border, bg = p.bg_elevated },
    BlinkCmpSignatureHelpActiveParameter = { fg = p.gold500, bold = true },
    BlinkCmpSource = { fg = p.fg_muted },

    -- ============================================
    -- snacks.nvim
    -- ============================================
    SnacksBackdrop = { bg = p.bg },
    SnacksDashboardDesc = { fg = p.fg_muted },
    SnacksDashboardFile = { fg = p.fg },
    SnacksDashboardDir = { fg = p.fg_muted },
    SnacksDashboardFooter = { fg = p.gold500, italic = true },
    SnacksDashboardHeader = { fg = p.gold500, bold = true },
    SnacksDashboardIcon = { fg = p.gold500 },
    SnacksDashboardKey = { fg = p.gold400 },
    SnacksDashboardSpecial = { fg = p.gold500 },
    SnacksDashboardTitle = { fg = p.gold500, bold = true },
    SnacksIndent = { fg = p.dark400 },
    SnacksIndentScope = { fg = p.gold600 },
    SnacksInputBorder = { fg = p.border },
    SnacksInputIcon = { fg = p.gold500 },
    SnacksInputNormal = { fg = p.fg, bg = p.bg_elevated },
    SnacksInputTitle = { fg = p.gold500, bold = true },
    SnacksNormal = { fg = p.fg, bg = p.bg_elevated },
    SnacksNotifierBorderDebug = { fg = p.fg_muted },
    SnacksNotifierBorderError = { fg = p.error },
    SnacksNotifierBorderInfo = { fg = p.info },
    SnacksNotifierBorderTrace = { fg = p.dark200 },
    SnacksNotifierBorderWarn = { fg = p.warning },
    SnacksNotifierDebug = { fg = p.fg_muted },
    SnacksNotifierError = { fg = p.error_light },
    SnacksNotifierIconDebug = { fg = p.fg_muted },
    SnacksNotifierIconError = { fg = p.error_light },
    SnacksNotifierIconInfo = { fg = p.info_light },
    SnacksNotifierIconTrace = { fg = p.dark100 },
    SnacksNotifierIconWarn = { fg = p.warning_light },
    SnacksNotifierInfo = { fg = p.info_light },
    SnacksNotifierTitleDebug = { fg = p.fg_muted, bold = true },
    SnacksNotifierTitleError = { fg = p.error_light, bold = true },
    SnacksNotifierTitleInfo = { fg = p.info_light, bold = true },
    SnacksNotifierTitleTrace = { fg = p.dark100, bold = true },
    SnacksNotifierTitleWarn = { fg = p.warning_light, bold = true },
    SnacksNotifierTrace = { fg = p.dark100 },
    SnacksNotifierWarn = { fg = p.warning_light },
    SnacksPickerBorder = { fg = p.border },
    SnacksPickerDir = { fg = p.fg_muted },
    SnacksPickerFile = { fg = p.fg },
    SnacksPickerIcon = { fg = p.gold500 },
    SnacksPickerIconDefault = { fg = p.fg_muted },
    SnacksPickerInput = { fg = p.fg, bg = p.bg_elevated },
    SnacksPickerInputBorder = { fg = p.gold500 },
    SnacksPickerInputIcon = { fg = p.gold500 },
    SnacksPickerInputTitle = { fg = p.gold500, bold = true },
    SnacksPickerList = { fg = p.fg, bg = p.bg },
    SnacksPickerListBorder = { fg = p.border },
    SnacksPickerListCursorLine = { bg = p.bg_element },
    SnacksPickerMatch = { fg = p.gold500, bold = true },
    SnacksPickerNormal = { fg = p.fg, bg = p.bg },
    SnacksPickerPreview = { fg = p.fg, bg = p.bg },
    SnacksPickerPreviewBorder = { fg = p.border },
    SnacksPickerPreviewTitle = { fg = p.gold500, bold = true },
    SnacksPickerPrompt = { fg = p.gold500 },
    SnacksPickerRow = { fg = p.fg_muted },
    SnacksPickerSelected = { fg = p.gold500, bold = true },
    SnacksPickerTitle = { fg = p.gold500, bold = true },
    SnacksPickerToggle = { fg = p.gold400 },
    SnacksPickerVirtText = { fg = p.fg_muted },
    SnacksScratchDesc = { fg = p.fg_muted },
    SnacksScratchFooter = { fg = p.gold500 },
    SnacksScratchKey = { fg = p.gold400 },
    SnacksWinBar = { fg = p.fg, bg = p.bg, bold = true },
    SnacksWinBarNC = { fg = p.fg_muted, bg = p.bg },
    SnacksZen = { bg = p.bg },

    -- ============================================
    -- mini.icons
    -- ============================================
    MiniIconsAzure = { fg = p.info_light },
    MiniIconsBlue = { fg = p.info },
    MiniIconsCyan = { fg = "#00bcd4" },
    MiniIconsGreen = { fg = p.success_light },
    MiniIconsGrey = { fg = p.fg_muted },
    MiniIconsOrange = { fg = p.warning_light },
    MiniIconsPurple = { fg = "#9c27b0" },
    MiniIconsRed = { fg = p.error_light },
    MiniIconsYellow = { fg = p.gold500 },

    -- ============================================
    -- mini.ai
    -- ============================================
    MiniAiBracket = { fg = p.gold500 },
    MiniAiQuote = { fg = p.gold500 },
    MiniAiFunctionCall = { fg = p.gold500 },
    MiniAiArgument = { fg = p.gold500 },

    -- ============================================
    -- mini.pairs
    -- ============================================
    MiniPairsOffscreen = { fg = p.fg_muted, italic = true },

    -- ============================================
    -- lazy.nvim
    -- ============================================
    LazyButton = { fg = p.fg, bg = p.bg_element },
    LazyButtonActive = { fg = p.bg, bg = p.gold500, bold = true },
    LazyComment = { fg = p.fg_muted },
    LazyCommit = { fg = p.gold400 },
    LazyCommitIssue = { fg = p.gold300 },
    LazyCommitScope = { fg = p.fg, italic = true },
    LazyCommitType = { fg = p.gold500, bold = true },
    LazyDimmed = { fg = p.dark200 },
    LazyDir = { fg = p.gold500 },
    LazyH1 = { fg = p.bg, bg = p.gold500, bold = true },
    LazyH2 = { fg = p.gold500, bold = true },
    LazyLocal = { fg = p.warning_light },
    LazyNoCond = { fg = p.error_light },
    LazyNormal = { fg = p.fg, bg = p.bg },
    LazyProgressDone = { fg = p.gold500 },
    LazyProgressTodo = { fg = p.dark200 },
    LazyProp = { fg = p.fg_muted },
    LazyReasonCmd = { fg = p.gold400 },
    LazyReasonEvent = { fg = p.warning_light },
    LazyReasonFt = { fg = p.info_light },
    LazyReasonImport = { fg = p.fg },
    LazyReasonKeys = { fg = p.gold300 },
    LazyReasonPlugin = { fg = p.gold500 },
    LazyReasonRequire = { fg = p.gold400 },
    LazyReasonRuntime = { fg = p.fg_muted },
    LazyReasonSource = { fg = p.success_light },
    LazyReasonStart = { fg = p.gold500 },
    LazySpecial = { fg = p.gold500 },
    LazyTaskError = { fg = p.error_light },
    LazyTaskOutput = { fg = p.fg },
    LazyUrl = { fg = p.info_light, underline = true },
    LazyValue = { fg = p.success_light },

    -- ============================================
    -- mason.nvim
    -- ============================================
    MasonError = { fg = p.error_light },
    MasonHeader = { fg = p.bg, bg = p.gold500, bold = true },
    MasonHeaderSecondary = { fg = p.bg, bg = p.info_light, bold = true },
    MasonHeading = { fg = p.gold500, bold = true },
    MasonHighlight = { fg = p.gold500 },
    MasonHighlightBlock = { fg = p.bg, bg = p.gold500 },
    MasonHighlightBlockBold = { fg = p.bg, bg = p.gold500, bold = true },
    MasonHighlightBlockBoldSecondary = { fg = p.bg, bg = p.info_light, bold = true },
    MasonHighlightBlockSecondary = { fg = p.bg, bg = p.info_light },
    MasonHighlightSecondary = { fg = p.info_light },
    MasonLink = { fg = p.info_light, underline = true },
    MasonMuted = { fg = p.fg_muted },
    MasonMutedBlock = { fg = p.fg_muted, bg = p.bg_element },
    MasonMutedBlockBold = { fg = p.fg_muted, bg = p.bg_element, bold = true },
    MasonNormal = { fg = p.fg, bg = p.bg },
    MasonWarning = { fg = p.warning_light },

    -- ============================================
    -- Telescope (if used)
    -- ============================================
    TelescopeBorder = { fg = p.border },
    TelescopeMatching = { fg = p.gold500, bold = true },
    TelescopeMultiIcon = { fg = p.gold400 },
    TelescopeMultiSelection = { fg = p.gold500 },
    TelescopeNormal = { fg = p.fg, bg = p.bg },
    TelescopePreviewBorder = { fg = p.border },
    TelescopePreviewNormal = { fg = p.fg, bg = p.bg },
    TelescopePreviewTitle = { fg = p.gold500, bold = true },
    TelescopePromptBorder = { fg = p.gold500 },
    TelescopePromptNormal = { fg = p.fg, bg = p.bg_elevated },
    TelescopePromptPrefix = { fg = p.gold500 },
    TelescopePromptTitle = { fg = p.gold500, bold = true },
    TelescopeResultsBorder = { fg = p.border },
    TelescopeResultsNormal = { fg = p.fg, bg = p.bg },
    TelescopeResultsTitle = { fg = p.gold500, bold = true },
    TelescopeSelection = { fg = p.fg, bg = p.bg_element },
    TelescopeSelectionCaret = { fg = p.gold500 },
    TelescopeTitle = { fg = p.gold500, bold = true },

    -- ============================================
    -- indent-blankline (if used)
    -- ============================================
    IblIndent = { fg = p.dark400 },
    IblScope = { fg = p.gold600 },
    IblWhitespace = { fg = p.dark400 },

    -- ============================================
    -- nvim-tree (if used)
    -- ============================================
    NvimTreeNormal = { fg = p.fg, bg = p.bg },
    NvimTreeNormalNC = { fg = p.fg, bg = p.bg },
    NvimTreeWinSeparator = { fg = p.border },
    NvimTreeRootFolder = { fg = p.gold500, bold = true },
    NvimTreeFolderName = { fg = p.gold500 },
    NvimTreeFolderIcon = { fg = p.gold500 },
    NvimTreeOpenedFolderName = { fg = p.gold400 },
    NvimTreeEmptyFolderName = { fg = p.fg_muted },
    NvimTreeIndentMarker = { fg = p.dark300 },
    NvimTreeGitDirty = { fg = p.git.change },
    NvimTreeGitNew = { fg = p.git.add },
    NvimTreeGitDeleted = { fg = p.git.delete },
    NvimTreeGitStaged = { fg = p.git.add },
    NvimTreeSpecialFile = { fg = p.gold300, underline = true },
    NvimTreeImageFile = { fg = p.fg },
    NvimTreeSymlink = { fg = p.info_light },

    -- ============================================
    -- neo-tree (if used)
    -- ============================================
    NeoTreeNormal = { fg = p.fg, bg = p.bg },
    NeoTreeNormalNC = { fg = p.fg, bg = p.bg },
    NeoTreeDimText = { fg = p.dark200 },
    NeoTreeDirectoryIcon = { fg = p.gold500 },
    NeoTreeDirectoryName = { fg = p.gold500 },
    NeoTreeDotfile = { fg = p.fg_muted },
    NeoTreeFileIcon = { fg = p.fg },
    NeoTreeFileName = { fg = p.fg },
    NeoTreeFileNameOpened = { fg = p.gold400 },
    NeoTreeFilterTerm = { fg = p.gold500, bold = true },
    NeoTreeFloatBorder = { fg = p.border },
    NeoTreeFloatTitle = { fg = p.gold500, bold = true },
    NeoTreeGitAdded = { fg = p.git.add },
    NeoTreeGitConflict = { fg = p.git.conflict },
    NeoTreeGitDeleted = { fg = p.git.delete },
    NeoTreeGitIgnored = { fg = p.git.ignore },
    NeoTreeGitModified = { fg = p.git.change },
    NeoTreeGitRenamed = { fg = p.git.rename },
    NeoTreeGitUnstaged = { fg = p.git.change },
    NeoTreeGitUntracked = { fg = p.git.add },
    NeoTreeGitStaged = { fg = p.git.add },
    NeoTreeHiddenByName = { fg = p.fg_muted },
    NeoTreeIndentMarker = { fg = p.dark300 },
    NeoTreeRootName = { fg = p.gold500, bold = true },
    NeoTreeSymbolicLinkTarget = { fg = p.info_light },
    NeoTreeTitleBar = { fg = p.gold500, bg = p.bg_elevated, bold = true },
    NeoTreeWinSeparator = { fg = p.border },

    -- ============================================
    -- Neogit (if used)
    -- ============================================
    NeogitBranch = { fg = p.gold500, bold = true },
    NeogitRemote = { fg = p.gold400 },
    NeogitHunkHeader = { fg = p.fg, bg = p.bg_element },
    NeogitHunkHeaderHighlight = { fg = p.gold500, bg = p.bg_element },
    NeogitDiffContext = { fg = p.fg, bg = p.bg },
    NeogitDiffContextHighlight = { fg = p.fg, bg = p.bg_elevated },
    NeogitDiffAdd = { fg = p.git.add, bg = p.success_bg },
    NeogitDiffAddHighlight = { fg = p.git.add, bg = p.success_bg },
    NeogitDiffDelete = { fg = p.git.delete, bg = p.error_bg },
    NeogitDiffDeleteHighlight = { fg = p.git.delete, bg = p.error_bg },

    -- ============================================
    -- Aerial (if used)
    -- ============================================
    AerialNormal = { fg = p.fg, bg = p.bg },
    AerialLine = { bg = p.bg_element },
    AerialGuide = { fg = p.dark300 },
    AerialClass = { fg = p.syntax.type, bold = true },
    AerialClassIcon = { fg = p.syntax.type },
    AerialFunction = { fg = p.syntax.func, bold = true },
    AerialFunctionIcon = { fg = p.syntax.func },
    AerialMethod = { fg = p.syntax.func },
    AerialMethodIcon = { fg = p.syntax.func },

    -- ============================================
    -- headlines.nvim (if used)
    -- ============================================
    Headline1 = { fg = p.gold500, bg = "#2d2a1f", bold = true },
    Headline2 = { fg = p.gold400, bg = "#2a2820", bold = true },
    Headline3 = { fg = p.gold300, bg = "#282621", bold = true },
    Headline4 = { fg = p.gold200, bg = "#262522", bold = true },
    Headline5 = { fg = p.gold100, bg = "#252423", bold = true },
    Headline6 = { fg = p.gold50, bg = "#242324", bold = true },
    Quote = { fg = p.dark100, italic = true },
    CodeBlock = { bg = p.bg_elevated },
    Dash = { fg = p.dark300 },
  }
end

return M
