local h = vim.api.nvim_set_hl
if vim.g.colors_name then
  vim.cmd("hi clear")
  vim.g.colors_name = nil
end
vim.o.termguicolors = true
vim.o.background = "dark"
vim.g.colors_name = "dawn_sky"

-- Terminal colors
vim.g.terminal_color_0 = "#090909"
vim.g.terminal_color_1 = "#D26473"
vim.g.terminal_color_2 = "#8EBD9C"
vim.g.terminal_color_3 = "#E5B085"
vim.g.terminal_color_4 = "#6B70A4"
vim.g.terminal_color_5 = "#BE6B88"
vim.g.terminal_color_6 = "#8B90C4"
vim.g.terminal_color_7 = "#C18496"
vim.g.terminal_color_8 = "#64342F"
vim.g.terminal_color_9 = "#FA9476"
vim.g.terminal_color_10 = "#A5D4B2"
vim.g.terminal_color_11 = "#F5C09A"
vim.g.terminal_color_12 = "#8B90C4"
vim.g.terminal_color_13 = "#D090A8"
vim.g.terminal_color_14 = "#A5A8D8"
vim.g.terminal_color_15 = "#F5E6E0"

-- Core UI Elements
h(0, "Normal", { bg = "#090909", fg = "#F5E6E0" })
h(0, "NormalNC", { bg = "#090909", fg = "#F5E6E0" })
h(0, "NormalSB", { bg = "#0E0C0C", fg = "#F5E6E0" })
h(0, "NormalFloat", { bg = "#0E0C0C", fg = "#F5E6E0" })
h(0, "FloatBorder", { fg = "#3A302D" })
h(0, "FloatTitle", { bold = true, fg = "#BE6B88" })

-- Cursor and Selection
h(0, "Cursor", { bg = "#FA9476", fg = "#090909" })
h(0, "lCursor", { link = "Cursor" })
h(0, "CursorIM", { link = "Cursor" })
h(0, "CursorLine", { bg = "#1A1518" })
h(0, "CursorColumn", { link = "CursorLine" })
h(0, "CursorLineNr", { fg = "#FA9476", bold = true })
h(0, "Visual", { bg = "#4A3A3D" })
h(0, "VisualNOS", { link = "Visual" })

-- Line Numbers and Signs
h(0, "LineNr", { fg = "#6B70A4" })
h(0, "SignColumn", { fg = "#82557A" })
h(0, "SignColumnSB", { link = "SignColumn" })
h(0, "FoldColumn", { fg = "#82557A" })
h(0, "Folded", { bg = "#1A1518", fg = "#9B7A94" })

-- Status Line
h(0, "StatusLine", { bg = "#BE6B88", fg = "#090909" })
h(0, "StatusLineNC", { bg = "#090909", fg = "#090909", sp = "#0E0C0C", underline = true })
h(0, "WinBar", { bg = "#090909", bold = true, fg = "#9B7A94" })
h(0, "WinBarNC", { bg = "#090909", bold = true, fg = "#82557A" })

-- Separators
h(0, "WinSeparator", { fg = "#2A201E" })
h(0, "VertSplit", { fg = "#2A201E" })

-- Tabs
h(0, "TabLine", { bg = "#1A1518", fg = "#9B7A94" })
h(0, "TabLineFill", { bg = "#0E0C0C" })
h(0, "TabLineSel", { bg = "#82557A", fg = "#090909" })

-- Search and Highlighting
h(0, "Search", { bg = "#5A4048" })
h(0, "IncSearch", { bg = "#FA9476", fg = "#090909" })
h(0, "CurSearch", { link = "IncSearch" })
h(0, "Substitute", { bg = "#D26473", fg = "#090909" })

-- Popup Menu
h(0, "Pmenu", { bg = "#0E0C0C", fg = "#F5E6E0" })
h(0, "PmenuSel", { bg = "#4A3A3D" })
h(0, "PmenuSbar", { link = "Pmenu" })
h(0, "PmenuThumb", { bg = "#4A3A3D" })
h(0, "WildMenu", { link = "Pmenu" })

-- Messages
h(0, "ErrorMsg", { fg = "#FA9476" })
h(0, "WarningMsg", { fg = "#E5B085" })
h(0, "ModeMsg", { bold = true, fg = "#E5B085" })
h(0, "MoreMsg", { bold = true, fg = "#8B90C4" })
h(0, "Question", { link = "MoreMsg" })

-- Spelling
h(0, "SpellBad", { sp = "#D26473", undercurl = true })
h(0, "SpellCap", { sp = "#E5B085", undercurl = true })
h(0, "SpellLocal", { sp = "#8B90C4", undercurl = true })
h(0, "SpellRare", { sp = "#8B90C4", undercurl = true })

-- Diff Mode
h(0, "DiffAdd", { link = "diffAdded" })
h(0, "DiffChange", { link = "diffChanged" })
h(0, "DiffDelete", { link = "diffRemoved" })
h(0, "DiffText", { bg = "#2A201E", fg = "#F5E6E0" })
h(0, "diffAdded", { link = "Added" })
h(0, "diffChanged", { link = "Changed" })
h(0, "diffRemoved", { link = "Removed" })
h(0, "Added", { bg = "#1A2520", fg = "#8EBD9C" })
h(0, "Changed", { bg = "#2A2418", fg = "#E5B085" })
h(0, "Removed", { bg = "#2A1618", fg = "#D26473" })

-- Basic Syntax Groups
h(0, "Comment", { fg = "#9B7A94", nocombine = true, italic = true })
h(0, "Constant", { fg = "#8B90C4" })
h(0, "String", { fg = "#E88D8E" })
h(0, "Character", { link = "String" })
h(0, "Number", { fg = "#8B90C4" })
h(0, "Boolean", { link = "Number" })
h(0, "Float", { link = "Number" })
h(0, "Identifier", { fg = "#F5E6E0" })
h(0, "Function", { fg = "#BE6B88" })
h(0, "Statement", { fg = "#FF9E80", bold = true })  -- Brightened for pop
h(0, "Conditional", { fg = "#FF9E80", bold = true })
h(0, "Repeat", { link = "Conditional" })
h(0, "Label", { link = "Conditional" })
h(0, "Operator", { fg = "#D090A8" })
h(0, "Keyword", { fg = "#FF9E80", bold = true })  -- Brightened coral for visibility
h(0, "Exception", { link = "Keyword" })
h(0, "PreProc", { fg = "#FA9476" })
h(0, "Include", { link = "PreProc" })
h(0, "Define", { link = "PreProc" })
h(0, "Macro", { link = "PreProc" })
h(0, "PreCondit", { link = "PreProc" })
h(0, "Type", { fg = "#9E658D" })
h(0, "StorageClass", { link = "Type" })
h(0, "Structure", { link = "Type" })
h(0, "Typedef", { link = "Type" })
h(0, "Special", { fg = "#C18496" })
h(0, "SpecialChar", { link = "Special" })
h(0, "Tag", { link = "Special" })
h(0, "Delimiter", { link = "Special" })
h(0, "SpecialComment", { link = "Special" })
h(0, "Debug", { link = "Special" })
h(0, "Underlined", { underline = true })
h(0, "Error", { fg = "#D26473" })
h(0, "Todo", { bg = "#E5B085", fg = "#090909", bold = true })
h(0, "Italic", { italic = true })
h(0, "Bold", { bold = true })

-- Additional UI Elements
h(0, "Conceal", { fg = "#564B48" })
h(0, "Directory", { fg = "#BE6B88" })
h(0, "NonText", { fg = "#564B48" })
h(0, "SpecialKey", { link = "NonText" })
h(0, "Title", { bold = true, fg = "#BE6B88" })
h(0, "Whitespace", { fg = "#2A201E" })
h(0, "EndOfBuffer", { fg = "#090909" })
h(0, "ColorColumn", { bg = "#1A1518" })
h(0, "MatchParen", { bg = "#5A4048", bold = true, fg = "#F5E6E0" })
h(0, "QuickFixLine", { link = "CursorLine" })

-- Treesitter Highlights
h(0, "@variable", { fg = "#F5E6E0" })
h(0, "@variable.builtin", { fg = "#8B90C4" })
h(0, "@variable.parameter", { fg = "#C18496" })
h(0, "@variable.parameter.builtin", { fg = "#8B90C4" })
h(0, "@variable.member", { fg = "#D090A8" })
h(0, "@constant", { fg = "#8B90C4" })
h(0, "@constant.builtin", { fg = "#8B90C4" })
h(0, "@constant.macro", { link = "Macro" })
h(0, "@module", { fg = "#9E658D" })
h(0, "@module.builtin", { fg = "#8B90C4" })
h(0, "@label", { link = "@tag" })
h(0, "@string", { fg = "#E88D8E" })
h(0, "@string.regexp", { fg = "#F5A5A6" })
h(0, "@string.escape", { bold = true, fg = "#F5A5A6" })
h(0, "@string.special", { fg = "#C18496" })
h(0, "@string.special.symbol", { link = "@constant" })
h(0, "@string.special.url", { fg = "#8B90C4", italic = true, underline = true })
h(0, "@character", { link = "@string" })
h(0, "@number", { fg = "#8B90C4" })
h(0, "@boolean", { link = "@number" })
h(0, "@float", { link = "@number" })
h(0, "@type", { fg = "#9E658D" })
h(0, "@type.builtin", { fg = "#FA9476" })
h(0, "@type.qualifier", { fg = "#FA9476" })
h(0, "@attribute", { link = "Constant" })
h(0, "@property", { link = "@variable.member" })
h(0, "@function", { fg = "#BE6B88" })
h(0, "@function.builtin", { fg = "#D090A8" })
h(0, "@function.call", { fg = "#BE6B88" })
h(0, "@function.macro", { link = "Macro" })
h(0, "@method", { link = "@function" })
h(0, "@method.call", { link = "@function.call" })
h(0, "@constructor", { fg = "#9E658D" })
h(0, "@operator", { fg = "#D090A8" })
h(0, "@keyword", { fg = "#FF9E80", bold = true })
h(0, "@keyword.operator", { fg = "#FA9476" })
h(0, "@keyword.function", { fg = "#FA9476" })
h(0, "@keyword.exception", { fg = "#8B90C4" })
h(0, "@keyword.storage", { link = "StorageClass" })
h(0, "@keyword.repeat", { link = "@repeat" })
h(0, "@keyword.return", { fg = "#FF9E80", bold = true })
h(0, "@keyword.conditional", { link = "@conditional" })
h(0, "@conditional", { fg = "#FF9E80", bold = true })
h(0, "@repeat", { fg = "#FF9E80", bold = true })
h(0, "@exception", { link = "@keyword.exception" })
h(0, "@include", { link = "Include" })
h(0, "@preproc", { link = "PreProc" })
h(0, "@define", { link = "Define" })
h(0, "@macro", { link = "Macro" })
h(0, "@punctuation", { fg = "#F5E6E0" })
h(0, "@punctuation.delimiter", { fg = "#F5E6E0" })
h(0, "@punctuation.bracket", { fg = "#F5E6E0" })
h(0, "@punctuation.special", { fg = "#D090A8" })
h(0, "@comment", { fg = "#9B7A94", italic = true })
h(0, "@comment.todo", { bg = "#82557A", fg = "#090909" })
h(0, "@comment.warning", { bg = "#E5B085", fg = "#090909" })
h(0, "@comment.error", { bg = "#D26473", fg = "#090909" })
h(0, "@comment.info", { bg = "#8B90C4", fg = "#090909" })
h(0, "@comment.hint", { bg = "#82557A", fg = "#090909" })
h(0, "@tag", { fg = "#8EBD9C" })
h(0, "@tag.builtin", { link = "@tag" })
h(0, "@tag.attribute", { link = "@variable.member" })
h(0, "@tag.delimiter", { fg = "#F5E6E0" })
h(0, "@none", { link = "NONE" })
h(0, "@conceal", { link = "Conceal" })

-- Markup
h(0, "@markup", { fg = "#F5E6E0" })
h(0, "@markup.strong", { bold = true, fg = "#F5E6E0" })
h(0, "@markup.italic", { fg = "#F5E6E0", italic = true })
h(0, "@markup.strikethrough", { fg = "#F5E6E0", strikethrough = true })
h(0, "@markup.underline", { fg = "#F5E6E0", underline = true })
h(0, "@markup.heading", { bold = true, fg = "#BE6B88" })
h(0, "@markup.heading.1", { bold = true, fg = "#FA9476" })
h(0, "@markup.heading.2", { bold = true, fg = "#BE6B88" })
h(0, "@markup.heading.3", { bold = true, fg = "#9E658D" })
h(0, "@markup.heading.4", { bold = true, fg = "#8B90C4" })
h(0, "@markup.heading.5", { bold = true, fg = "#82557A" })
h(0, "@markup.heading.6", { bold = true, fg = "#6B70A4" })
h(0, "@markup.quote", { fg = "#8EBD9C" })
h(0, "@markup.math", { fg = "#8B90C4" })
h(0, "@markup.environment", { fg = "#FA9476" })
h(0, "@markup.environment.name", { fg = "#BE6B88" })
h(0, "@markup.link", { fg = "#F5E6E0", underline = true })
h(0, "@markup.link.label", { link = "Special" })
h(0, "@markup.link.uri", { fg = "#8B90C4", italic = true, underline = true })
h(0, "@markup.raw", { fg = "#F5E6E0", italic = true })
h(0, "@markup.list", { fg = "#8B90C4" })
h(0, "@markup.list.checked", { fg = "#8EBD9C" })
h(0, "@markup.list.unchecked", { fg = "#82557A" })

-- Diff
h(0, "@diff.plus", { link = "diffAdded" })
h(0, "@diff.minus", { link = "diffRemoved" })
h(0, "@diff.delta", { link = "diffChanged" })

-- LSP Semantic Tokens
h(0, "@lsp.type.class", { link = "@function" })
h(0, "@lsp.type.enum", { link = "@type" })
h(0, "@lsp.type.interface", { link = "@interface" })
h(0, "@lsp.type.keyword", { link = "@keyword" })
h(0, "@lsp.type.namespace", { link = "@namespace" })
h(0, "@lsp.type.parameter", { link = "@variable.parameter" })
h(0, "@lsp.type.property", { fg = "#D090A8" })
h(0, "@lsp.type.variable", { fg = "#F5E6E0" })
h(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
h(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
h(0, "@lsp.typemod.operator.injected", { link = "@operator" })
h(0, "@lsp.typemod.string.injected", { link = "@string" })
h(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
h(0, "@lsp.typemod.variable.injected", { link = "@variable" })

-- Diagnostics
h(0, "DiagnosticError", { fg = "#D26473" })
h(0, "DiagnosticWarn", { fg = "#E5B085" })
h(0, "DiagnosticInfo", { fg = "#8B90C4" })
h(0, "DiagnosticHint", { fg = "#82557A" })
h(0, "DiagnosticOk", { fg = "#8EBD9C" })
h(0, "DiagnosticSignError", { link = "DiagnosticError" })
h(0, "DiagnosticSignWarn", { link = "DiagnosticWarn" })
h(0, "DiagnosticSignInfo", { link = "DiagnosticInfo" })
h(0, "DiagnosticSignHint", { link = "DiagnosticHint" })
h(0, "DiagnosticSignOk", { link = "DiagnosticOk" })
h(0, "DiagnosticVirtualTextError", { bg = "NONE", fg = "#D26473" })
h(0, "DiagnosticVirtualTextWarn", { bg = "NONE", fg = "#E5B085" })
h(0, "DiagnosticVirtualTextInfo", { bg = "NONE", fg = "#8B90C4" })
h(0, "DiagnosticVirtualTextHint", { bg = "NONE", fg = "#82557A" })
h(0, "DiagnosticVirtualTextOk", { bg = "NONE", fg = "#8EBD9C" })
h(0, "DiagnosticUnderlineError", { sp = "#D26473", undercurl = true })
h(0, "DiagnosticUnderlineWarn", { sp = "#E5B085", undercurl = true })
h(0, "DiagnosticUnderlineInfo", { sp = "#8B90C4", undercurl = true })
h(0, "DiagnosticUnderlineHint", { sp = "#82557A", undercurl = true })
h(0, "DiagnosticUnderlineOk", { sp = "#8EBD9C", undercurl = true })

-- LSP
h(0, "LspReferenceText", { bg = "#4A3A3D" })
h(0, "LspReferenceRead", { bg = "#4A3A3D" })
h(0, "LspReferenceWrite", { bg = "#4A3A3D" })
h(0, "LspCodeLens", { fg = "#564B48" })
h(0, "LspCodeLensSeparator", { fg = "#82557A" })
h(0, "LspSignatureActiveParameter", { fg = "#4A3A3D" })
h(0, "LspInlayHint", { bg = "#1A1518", fg = "#564B48" })

-- Git Signs
h(0, "GitSignsAdd", { fg = "#8EBD9C" })
h(0, "GitSignsChange", { fg = "#E5B085" })
h(0, "GitSignsDelete", { fg = "#D26473" })
h(0, "GitSignsCurrentLineBlame", { fg = "#564B48" })
h(0, "GitGutterAdd", { fg = "#8EBD9C" })
h(0, "GitGutterChange", { fg = "#E5B085" })
h(0, "GitGutterDelete", { fg = "#D26473" })

-- NvimTree
h(0, "NvimTreeNormal", { link = "NormalSB" })
h(0, "NvimTreeNormalNC", { link = "NvimTreeNormal" })
h(0, "NvimTreeRootFolder", { bold = true, fg = "#F5E6E0" })
h(0, "NvimTreeGitDirty", { fg = "#E5B085" })
h(0, "NvimTreeGitNew", { fg = "#8EBD9C" })
h(0, "NvimTreeGitDeleted", { fg = "#D26473" })
h(0, "NvimTreeGitStaged", { fg = "#8EBD9C" })
h(0, "NvimTreeGitMerge", { fg = "#BE6B88" })
h(0, "NvimTreeGitRenamed", { fg = "#D090A8" })
h(0, "NvimTreeGitIgnored", { fg = "#564B48" })
h(0, "NvimTreeSymlink", { fg = "#BE6B88" })
h(0, "NvimTreeFolderName", { fg = "#F5E6E0" })
h(0, "NvimTreeFolderIcon", { fg = "#F5E6E0" })
h(0, "NvimTreeOpenedFolderName", { bold = true, fg = "#F5E6E0" })
h(0, "NvimTreeEmptyFolderName", { fg = "#82557A" })
h(0, "NvimTreeOpenedFile", { fg = "#8B90C4" })
h(0, "NvimTreeSpecialFile", { fg = "#E5B085", underline = true })
h(0, "NvimTreeIndentMarker", { fg = "#564B48" })
h(0, "NvimTreeImageFile", { fg = "#C18496" })
h(0, "NvimTreeEndOfBuffer", { fg = "#0E0C0C" })

-- Neo-tree
h(0, "NeoTreeNormal", { link = "NormalSB" })
h(0, "NeoTreeNormalNC", { link = "NeoTreeNormal" })
h(0, "NeoTreeTitleBar", { bg = "#BE6B88", fg = "#090909" })
h(0, "NeoTreeEndOfBuffer", { fg = "#0E0C0C" })
h(0, "NeoTreeIndentMarker", { fg = "#564B48" })
h(0, "NeoTreeRootName", { bold = true, fg = "#F5E6E0" })
h(0, "NeoTreeDirectoryName", { fg = "#F5E6E0" })
h(0, "NeoTreeDirectoryIcon", { fg = "#F5E6E0" })
h(0, "NeoTreeDotfile", { fg = "#564B48" })
h(0, "NeoTreeSymbolicLinkTarget", { fg = "#BE6B88" })
h(0, "NeoTreeFileName", { fg = "#F5E6E0" })
h(0, "NeoTreeFileNameOpened", { fg = "#8B90C4" })
h(0, "NeoTreeDimText", { link = "Conceal" })
h(0, "NeoTreeGitModified", { fg = "#E5B085" })
h(0, "NeoTreeGitAdded", { fg = "#8EBD9C" })
h(0, "NeoTreeGitDeleted", { fg = "#D26473" })
h(0, "NeoTreeGitConflict", { fg = "#FA9476", italic = true })
h(0, "NeoTreeGitIgnored", { fg = "#82557A" })
h(0, "NeoTreeGitUntracked", { fg = "#A5A8D8" })

-- Telescope
h(0, "TelescopeNormal", { link = "NormalFloat" })
h(0, "TelescopeBorder", { link = "FloatBorder" })
h(0, "TelescopePromptNormal", { link = "NormalFloat" })
h(0, "TelescopePromptBorder", { link = "FloatBorder" })
h(0, "TelescopeResultsNormal", { link = "NormalFloat" })
h(0, "TelescopeResultsBorder", { link = "FloatBorder" })
h(0, "TelescopePreviewNormal", { link = "NormalFloat" })
h(0, "TelescopePreviewBorder", { link = "FloatBorder" })
h(0, "TelescopeSelection", { link = "CursorLine" })
h(0, "TelescopeSelectionCaret", { fg = "#FA9476" })
h(0, "TelescopeMatching", { link = "Search" })
h(0, "TelescopePromptTitle", { fg = "#BE6B88", bold = true })
h(0, "TelescopeResultsTitle", { fg = "#BE6B88", bold = true })
h(0, "TelescopePreviewTitle", { fg = "#BE6B88", bold = true })

-- CMP (Completion)
h(0, "CmpItemAbbr", { fg = "#F5E6E0" })
h(0, "CmpItemAbbrMatch", { fg = "#BE6B88" })
h(0, "CmpItemAbbrMatchFuzzy", { fg = "#BE6B88" })
h(0, "CmpItemAbbrDeprecated", { fg = "#FA9476", strikethrough = true })
h(0, "CmpItemKindDefault", { fg = "#82557A" })
h(0, "CmpItemMenu", { link = "Comment" })
h(0, "CmpItemKindVariable", { link = "@variable" })
h(0, "CmpItemKindKeyword", { link = "Keyword" })
h(0, "CmpItemKindConstant", { link = "@constant" })
h(0, "CmpItemKindReference", { link = "Keyword" })
h(0, "CmpItemKindValue", { link = "Keyword" })
h(0, "CmpItemKindFunction", { link = "Function" })
h(0, "CmpItemKindMethod", { link = "Function" })
h(0, "CmpItemKindConstructor", { link = "@constructor" })
h(0, "CmpItemKindInterface", { link = "Constant" })
h(0, "CmpItemKindEnum", { link = "Constant" })
h(0, "CmpItemKindUnit", { link = "Constant" })
h(0, "CmpItemKindClass", { link = "Type" })
h(0, "CmpItemKindStruct", { link = "Type" })
h(0, "CmpItemKindModule", { link = "@module" })
h(0, "CmpItemKindProperty", { link = "@property" })
h(0, "CmpItemKindField", { link = "@variable.member" })
h(0, "CmpItemKindTypeParameter", { link = "@variable.member" })
h(0, "CmpItemKindEnumMember", { link = "@variable.member" })
h(0, "CmpItemKindOperator", { link = "Operator" })
h(0, "CmpItemKindSnippet", { fg = "#82557A" })
h(0, "CmpItemKindEvent", { link = "Constant" })
h(0, "CmpDocumentation", { bg = "#0E0C0C", fg = "#F5E6E0" })
h(0, "CmpDocumentationBorder", { bg = "#0E0C0C", fg = "#4A3A3D" })

-- WhichKey
h(0, "WhichKey", { link = "Identifier" })
h(0, "WhichKeyFloat", { bg = "#0E0C0C" })
h(0, "WhichKeySeparator", { link = "Comment" })
h(0, "WhichKeySeperator", { link = "Comment" })
h(0, "WhichKeyGroup", { link = "Function" })
h(0, "WhichKeyDesc", { link = "Keyword" })
h(0, "WhichKeyValue", { link = "Comment" })

-- Indent Blankline
h(0, "IndentBlanklineChar", { fg = "#2A201E" })
h(0, "IndentBlanklineContextChar", { fg = "#564B48" })
h(0, "IndentBlanklineContextStart", { sp = "#FA9476", underline = true })

-- Neogit
h(0, "NeogitBranch", { fg = "#E5B085" })
h(0, "NeogitRemote", { fg = "#82557A" })
h(0, "NeogitHunkHeader", { bg = "#1A1518", fg = "#8B90C4" })
h(0, "NeogitHunkHeaderHighlight", { bg = "#4A3A3D", fg = "#8B90C4" })
h(0, "NeogitDiffContextHighlight", { bg = "#1A1518" })
h(0, "NeogitDiffAdd", { fg = "#8EBD9C" })
h(0, "NeogitDiffAddHighlight", { bg = "#1A2520" })
h(0, "NeogitDiffDelete", { fg = "#D26473" })
h(0, "NeogitDiffDeleteHighlight", { bg = "#2A1618" })
h(0, "NeogitNotificationInfo", { fg = "#8B90C4" })
h(0, "NeogitNotificationWarning", { fg = "#E5B085" })
h(0, "NeogitNotificationError", { fg = "#D26473" })

-- Mini.nvim suite
h(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
h(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
h(0, "MiniClueBorder", { link = "FloatBorder" })
h(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
h(0, "MiniClueDescSingle", { link = "NormalFloat" })
h(0, "MiniClueNextKey", { fg = "#8B90C4" })
h(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
h(0, "MiniClueSeparator", { fg = "#82557A" })
h(0, "MiniClueTitle", { link = "FloatTitle" })
h(0, "MiniCompletionActiveParameter", { underline = true })
h(0, "MiniCursorword", { bg = "#4A3A3D" })
h(0, "MiniCursorwordCurrent", { bg = "#4A3A3D" })
h(0, "MiniDepsChangeAdded", { link = "diffAdded" })
h(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
h(0, "MiniDepsHint", { link = "DiagnosticHint" })
h(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
h(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
h(0, "MiniDepsPlaceholder", { link = "Comment" })
h(0, "MiniDepsTitle", { link = "Title" })
h(0, "MiniDepsTitleError", { link = "DiffDelete" })
h(0, "MiniDepsTitleSame", { link = "DiffText" })
h(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
h(0, "MiniDiffOverAdd", { link = "DiffAdd" })
h(0, "MiniDiffOverChange", { bg = "#2A201E", fg = "#F5E6E0" })
h(0, "MiniDiffOverContext", { link = "DiffChange" })
h(0, "MiniDiffOverDelete", { link = "DiffDelete" })
h(0, "MiniDiffSignAdd", { fg = "#8EBD9C" })
h(0, "MiniDiffSignChange", { fg = "#E5B085" })
h(0, "MiniDiffSignDelete", { fg = "#D26473" })
h(0, "MiniFilesBorder", { link = "FloatBorder" })
h(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
h(0, "MiniFilesCursorLine", { link = "CursorLine" })
h(0, "MiniFilesDirectory", { link = "Directory" })
h(0, "MiniFilesFile", { fg = "#F5E6E0" })
h(0, "MiniFilesNormal", { link = "NormalFloat" })
h(0, "MiniFilesTitle", { link = "FloatTitle" })
h(0, "MiniFilesTitleFocused", { bold = true, fg = "#F5E6E0" })
h(0, "MiniHipatternsFixme", { bg = "#D26473", bold = true, fg = "#090909" })
h(0, "MiniHipatternsHack", { bg = "#E5B085", bold = true, fg = "#090909" })
h(0, "MiniHipatternsNote", { bg = "#8B90C4", bold = true, fg = "#090909" })
h(0, "MiniHipatternsTodo", { bg = "#82557A", bold = true, fg = "#090909" })
h(0, "MiniIconsAzure", { fg = "#8B90C4" })
h(0, "MiniIconsBlue", { fg = "#6B70A4" })
h(0, "MiniIconsCyan", { fg = "#A5A8D8" })
h(0, "MiniIconsGreen", { fg = "#8EBD9C" })
h(0, "MiniIconsGrey", { fg = "#F5E6E0" })
h(0, "MiniIconsOrange", { fg = "#FA9476" })
h(0, "MiniIconsPurple", { fg = "#BE6B88" })
h(0, "MiniIconsRed", { fg = "#D26473" })
h(0, "MiniIconsYellow", { fg = "#E5B085" })
h(0, "MiniIndentscopeSymbol", { link = "Delimiter" })
h(0, "MiniIndentscopePrefix", { nocombine = true })
h(0, "MiniJump", { link = "SpellRare" })
h(0, "MiniJump2dDim", { link = "Comment" })
h(0, "MiniJump2dSpot", { bold = true, fg = "#BE6B88" })
h(0, "MiniJump2dSpotAhead", { fg = "#8B90C4", nocombine = true })
h(0, "MiniJump2dSpotUnique", { bold = true, fg = "#E5B085" })
h(0, "MiniMapNormal", { link = "NormalFloat" })
h(0, "MiniMapSymbolCount", { link = "Special" })
h(0, "MiniMapSymbolLine", { fg = "#8B90C4" })
h(0, "MiniMapSymbolView", { fg = "#4A3A3D" })
h(0, "MiniNotifyBorder", { link = "FloatBorder" })
h(0, "MiniNotifyNormal", { link = "NormalFloat" })
h(0, "MiniNotifyTitle", { link = "FloatTitle" })
h(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
h(0, "MiniPickBorder", { link = "FloatBorder" })
h(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
h(0, "MiniPickBorderText", { link = "FloatTitle" })
h(0, "MiniPickIconDirectory", { link = "Directory" })
h(0, "MiniPickIconFile", { link = "MiniPickNormal" })
h(0, "MiniPickHeader", { fg = "#8B90C4" })
h(0, "MiniPickMatchCurrent", { link = "CursorLine" })
h(0, "MiniPickMatchMarked", { link = "Visual" })
h(0, "MiniPickMatchRanges", { fg = "#E5B085" })
h(0, "MiniPickNormal", { link = "NormalFloat" })
h(0, "MiniPickPreviewLine", { link = "CursorLine" })
h(0, "MiniPickPreviewRegion", { link = "IncSearch" })
h(0, "MiniPickPrompt", { fg = "#8B90C4" })
h(0, "MiniStarterCurrent", { nocombine = true })
h(0, "MiniStarterFooter", { fg = "#82557A", italic = true })
h(0, "MiniStarterHeader", { fg = "#6B70A4" })
h(0, "MiniStarterInactive", { link = "Comment" })
h(0, "MiniStarterItem", { link = "Normal" })
h(0, "MiniStarterItemBullet", { fg = "#2A201E" })
h(0, "MiniStarterItemPrefix", { fg = "#E5B085" })
h(0, "MiniStarterSection", { link = "Special" })
h(0, "MiniStarterQuery", { fg = "#8B90C4" })
h(0, "MiniStatuslineDevinfo", { bg = "#1A1518", fg = "#F5E6E0" })
h(0, "MiniStatuslineFileinfo", { bg = "#1A1518", fg = "#F5E6E0" })
h(0, "MiniStatuslineFilename", { bg = "#090909", fg = "#9B7A94" })
h(0, "MiniStatuslineInactive", { bg = "#0E0C0C", fg = "#9B7A94" })
h(0, "MiniStatuslineModeCommand", { bg = "#BE6B88", bold = true, fg = "#090909" })
h(0, "MiniStatuslineModeInsert", { bg = "#8EBD9C", bold = true, fg = "#090909" })
h(0, "MiniStatuslineModeNormal", { bg = "#6B70A4", bold = true, fg = "#090909" })
h(0, "MiniStatuslineModeOther", { bold = true, fg = "#090909" })
h(0, "MiniStatuslineModeReplace", { bg = "#D26473", bold = true, fg = "#090909" })
h(0, "MiniStatuslineModeVisual", { bg = "#E5B085", bold = true, fg = "#090909" })
h(0, "MiniSurround", { link = "IncSearch" })
h(0, "MiniTablineCurrent", { bg = "#BE6B88", bold = true, fg = "#090909" })
h(0, "MiniTablineFill", { link = "TabLineFill" })
h(0, "MiniTablineHidden", { bg = "#090909", fg = "#F5E6E0" })
h(0, "MiniTablineModifiedCurrent", { bg = "#0E0C0C", bold = true, fg = "#BE6B88" })
h(0, "MiniTablineModifiedHidden", { bg = "#F5E6E0", fg = "#090909" })
h(0, "MiniTablineModifiedVisible", { bg = "#0E0C0C", fg = "#9E658D" })
h(0, "MiniTablineTabpagesection", { bg = "#4A3A3D", bold = true, fg = "NONE" })
h(0, "MiniTablineVisible", { bg = "#9E658D", fg = "#090909" })
h(0, "MiniTestEmphasis", { bold = true })
h(0, "MiniTestFail", { bold = true, fg = "#D26473" })
h(0, "MiniTestPass", { bold = true, fg = "#8EBD9C" })
h(0, "MiniTrailspace", { bg = "#D26473" })

-- Notify
h(0, "NotifyERRORBorder", { link = "NotifyERRORTitle" })
h(0, "NotifyWARNBorder", { link = "NotifyWARNTitle" })
h(0, "NotifyINFOBorder", { link = "NotifyINFOTitle" })
h(0, "NotifyDEBUGBorder", { link = "NotifyDEBUGTitle" })
h(0, "NotifyTRACEBorder", { link = "NotifyTRACETitle" })
h(0, "NotifyERRORIcon", { link = "NotifyERRORTitle" })
h(0, "NotifyWARNIcon", { link = "NotifyWARNTitle" })
h(0, "NotifyINFOIcon", { link = "NotifyINFOTitle" })
h(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGTitle" })
h(0, "NotifyTRACEIcon", { link = "NotifyTRACETitle" })
h(0, "NotifyERRORTitle", { fg = "#D26473" })
h(0, "NotifyWARNTitle", { fg = "#E5B085" })
h(0, "NotifyINFOTitle", { fg = "#8EBD9C" })
h(0, "NotifyDEBUGTitle", { fg = "#F5E6E0" })
h(0, "NotifyTRACETitle", { fg = "#BE6B88" })
h(0, "NotifyERRORBody", { link = "NotifyERRORTitle" })
h(0, "NotifyWARNBody", { link = "NotifyWARNTitle" })
h(0, "NotifyINFOBody", { link = "NotifyINFOTitle" })
h(0, "NotifyDEBUGBody", { link = "NotifyDEBUGTitle" })
h(0, "NotifyTRACEBody", { link = "NotifyTRACETitle" })

-- Trouble
h(0, "LspTroubleNormal", { bg = "#0E0C0C", fg = "#82557A" })
h(0, "LspTroubleText", { fg = "#82557A" })
h(0, "LspTroubleCount", { bg = "#82557A", fg = "#BE6B88" })

-- Dashboard
h(0, "DashboardCenter", { link = "String" })
h(0, "DashboardFooter", { fg = "#8B90C4", italic = true })
h(0, "DashboardHeader", { link = "Title" })
h(0, "DashboardShortCut", { link = "Identifier" })

-- DAP UI
h(0, "DapUIBreakpointsCurrentLine", { link = "DapUIThread" })
h(0, "DapUIBreakpointsDisabledLine", { fg = "#82557A" })
h(0, "DapUIBreakpointsInfo", { link = "DapUIWatchesValue" })
h(0, "DapUIBreakpointsPath", { link = "DapUIScope" })
h(0, "DapUIDecoration", { link = "DapUIScope" })
h(0, "DapUIFloatBorder", { link = "DapUIScope" })
h(0, "DapUILineNumber", { link = "DapUIScope" })
h(0, "DapUIModifiedValue", { bold = true, fg = "#A5A8D8" })
h(0, "DapUIPlayPause", { link = "DapUIWatchesValue" })
h(0, "DapUIRestart", { link = "DapUIWatchesValue" })
h(0, "DapUIScope", { fg = "#A5A8D8" })
h(0, "DapUISource", { link = "DapUIType" })
h(0, "DapUIStepBack", { link = "DapUIScope" })
h(0, "DapUIStepInto", { link = "DapUIScope" })
h(0, "DapUIStepOut", { link = "DapUIScope" })
h(0, "DapUIStepOver", { link = "DapUIScope" })
h(0, "DapUIStop", { link = "DapUIWatchesEmpty" })
h(0, "DapUIStoppedThread", { link = "DapUIScope" })
h(0, "DapUIThread", { bold = true, fg = "#8EBD9C" })
h(0, "DapUIType", { fg = "#BE6B88" })
h(0, "DapUIUnavailable", { link = "DapUIBreakpointsDisabledLine" })
h(0, "DapUIWatchesEmpty", { fg = "#D26473" })
h(0, "DapUIWatchesError", { link = "DapUIWatchesEmpty" })
h(0, "DapUIWatchesValue", { fg = "#8EBD9C" })
h(0, "DapUIWinSelect", { link = "DapUIModifiedValue" })

-- FZF-Lua
h(0, "FzfLuaNormal", { link = "Normal" })
h(0, "FzfLuaBorder", { link = "Normal" })
h(0, "FzfLuaTitle", { link = "Title" })
h(0, "FzfLuaCursor", { link = "Cursor" })
h(0, "FzfLuaCursorLine", { link = "CursorLine" })
h(0, "FzfLuaCursorLineNr", { link = "CursorLineNr" })
h(0, "FzfLuaSearch", { link = "IncSearch" })
h(0, "FzfLuaScrollBorderEmpty", { link = "FzfLuaBorder" })
h(0, "FzfLuaScrollBorderFull", { link = "FzfLuaBorder" })
h(0, "FzfLuaScrollFloatEmpty", { link = "PmenuSbar" })
h(0, "FzfLuaScrollFloatFull", { link = "PmenuThumb" })
h(0, "FzfLuaHelpNormal", { link = "FzfLuaNormal" })
h(0, "FzfLuaHelpBorder", { link = "FzfLuaBorder" })

-- Fidget
h(0, "FidgetTitle", { link = "Title" })
h(0, "FidgetTask", { link = "LineNr" })

-- Coc.nvim
h(0, "CocExplorerNormalFloat", { link = "NormalSB" })
h(0, "CocExplorerFileRootName", { bold = true, fg = "#F5E6E0" })
h(0, "CocExplorerFileDirectory", { bold = true, fg = "#F5E6E0" })
h(0, "CocExplorerGitPathChange_Internal", { fg = "#D090A8" })
h(0, "CocExplorerGitAdded", { fg = "#8EBD9C" })
h(0, "CocExplorerGitModified", { fg = "#E5B085" })
h(0, "CocExplorerGitContentChange", { fg = "#E5B085" })
h(0, "CocExplorerGitPathChange", { fg = "#D090A8" })
h(0, "CocExplorerGitIgnored", { fg = "#564B48" })
h(0, "CocExplorerGitUntracked", { fg = "#564B48" })
h(0, "CocInlayHint", { bg = "#1A1518", fg = "#564B48" })

-- TreeSitter Context
h(0, "TreesitterContext", { bg = "#1A1518" })

-- Language-specific tweaks
-- Lua
h(0, "@constructor.lua", { fg = "#F5E6E0" })
h(0, "@operator.lua", { fg = "#FA9476" })
h(0, "@function.builtin.lua", { fg = "#8B90C4" })
h(0, "@module.builtin.lua", { fg = "#8B90C4" })
h(0, "@property.lua", { fg = "#F5E6E0" })
h(0, "@property.luadoc", { link = "@property.lua" })
h(0, "@variable.member.luadoc", { link = "@property.luadoc" })
h(0, "@operator.luadoc", { fg = "#F5E6E0" })
h(0, "@markup.list.luadoc", { fg = "#F5E6E0" })
h(0, "@lsp.type.variable.lua", {  })
h(0, "luaTable", {  })
h(0, "luaFunction", { link = "Keyword" })

-- Python
h(0, "@variable.member.python", { fg = "#F5E6E0" })
h(0, "@type.builtin.python", { link = "@constant" })
h(0, "@variable.builtin.python", { link = "@constant" })
h(0, "@module.python", {  })

-- JavaScript/TypeScript
h(0, "@tag.javascript", { link = "@type.javascript" })
h(0, "@tag.tsx", { link = "@type.tsx" })
h(0, "@tag.delimiter.javascript", { link = "@tag.attribute.javascript" })
h(0, "@tag.delimiter.tsx", { link = "@tag.attribute.tsx" })

-- JSON
h(0, "@property.json", { link = "@tag" })
h(0, "jsonKeyword", { fg = "#8EBD9C" })
h(0, "jsonNull", { link = "Constant" })

-- YAML
h(0, "@property.yaml", { link = "@tag" })
h(0, "yamlBlockMappingKey", { fg = "#8EBD9C" })
h(0, "yamlFlowMappingKey", { fg = "#8EBD9C" })

-- Markdown
h(0, "@punctuation.delimiter.markdown", { fg = "#F5E6E0" })
h(0, "@punctuation.delimiter.markdown_inline", { fg = "#F5E6E0" })
h(0, "@markup.quote.markdown", { fg = "#8EBD9C" })

-- HTML/XML
h(0, "htmlTag", { fg = "#8EBD9C" })
h(0, "xmlTagName", { link = "htmlTag" })
h(0, "xmlAttrib", { link = "htmlTag" })
h(0, "@constant.html", { link = "@tag" })
h(0, "@markup.heading.html", { fg = "#F5E6E0" })

-- CSS/SCSS
h(0, "@type.css", { link = "htmlTag" })
h(0, "cssBraces", { fg = "#F5E6E0" })
h(0, "cssMedia", { link = "Keyword" })
h(0, "cssProp", { link = "Constant" })
h(0, "cssPseudoClassId", { link = "Function" })
h(0, "lessAmpersand", { link = "Function" })
h(0, "lessClassCall", { link = "Function" })
h(0, "lessCssAttribute", { link = "Constant" })
h(0, "lessFunction", { link = "Constant" })
h(0, "lessClass", { link = "Function" })
h(0, "lessVariable", { fg = "#F5E6E0" })
h(0, "@property.scss", { link = "@constant" })
h(0, "@variable.scss", { link = "@variable.parameter" })

-- Bash
h(0, "@operator.bash", { fg = "#FA9476" })
h(0, "@function.builtin.bash", { fg = "#FA9476" })
h(0, "@function.call.bash", { fg = "#8B90C4" })
h(0, "@number.bash", {  })
h(0, "@punctuation.delimiter.bash", { fg = "#FA9476" })
h(0, "@markup.list.bash", { link = "@punctuation.bash" })

-- C/C++
h(0, "@type.c", {  })

-- C#
h(0, "@module.c_sharp", { fg = "#9E658D" })

-- Go
h(0, "@module.go", {  })

-- Rust
h(0, "@constant.builtin.rust", { fg = "#9E658D" })
h(0, "@module.rust", {  })
h(0, "@keyword.directive.rust", { fg = "#8B90C4" })
h(0, "@keyword.storage.lifetime.rust", { link = "@tag.rust" })
h(0, "@keyword.storage.lifetime.punctuation.rust", { link = "@markup.list.rust" })

-- Ruby
h(0, "@label.ruby", { fg = "#8B90C4" })
h(0, "@string.special.symbol.ruby", { link = "@constant" })

-- Elixir
h(0, "@module.elixir", { link = "@type" })

-- PHP
h(0, "@module.php", { link = "@constructor.php" })

-- SQL
h(0, "@variable.member.sql", { link = "@constant" })
h(0, "@type.sql", { link = "@variable" })
h(0, "@variable.sql", { link = "@constant" })

-- Nix
h(0, "@variable.member.nix", { link = "@variable.member" })
h(0, "@variable.parameter.nix", { link = "@variable.parameter" })
h(0, "@string.special.path.nix", { link = "@string" })

-- Make
h(0, "@string.special.symbol.make", { link = "@function" })
h(0, "@function.builtin.make", { link = "@constant" })

-- Vim
h(0, "@variable.parameter.vimdoc", { fg = "#9E658D" })
h(0, "@label.vimdoc", { link = "@keyword" })

-- Gitignore
h(0, "@string.special.path.gitignore", { fg = "#BE6B88" })

-- Diff
h(0, "diffFile", { fg = "#8B90C4" })
h(0, "diffNewFile", { fg = "#82557A" })
h(0, "diffOldFile", { fg = "#E5B085" })
h(0, "diffLine", { fg = "#8B90C4" })
h(0, "diffIndexLine", { fg = "#FA9476" })

-- QuickFix
h(0, "qfLineNr", { link = "lineNr" })
h(0, "qfFileName", { link = "Directory" })

